apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Removed cluster-wide from the URL since it doesn't exist in 25.0.0
  - https://github.com/keycloak/keycloak-k8s-resources//kubernetes?ref=25.0.0

patches:
  # 1. Update the Operator to watch all namespaces
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak-operator
      spec:
        template:
          spec:
            containers:
              - name: operator
                env:
                  - name: WATCH_NAMESPACES
                    value: ""

  # 2. Promote the namespace-scoped Role to a ClusterRole
  - target:
      kind: Role
      name: keycloak-operator-role
    patch: |-
      - op: replace
        path: /kind
        value: ClusterRole

  # 3. Promote the RoleBinding to a ClusterRoleBinding
  - target:
      kind: RoleBinding
      name: keycloak-operator-role-binding
    patch: |-
      - op: replace
        path: /kind
        value: ClusterRoleBinding
      - op: replace
        path: /roleRef/kind
        value: ClusterRole