apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak-system

resources:
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.0/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.0/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.0/kubernetes/kubernetes.yml

patches:
  # 1. Update the Operator to watch all namespaces
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak-operator
      spec:
        template:
          spec:
            containers:
              - name: operator
                env:
                  - name: WATCH_NAMESPACES
                    value: ""

  # 2. Promote the namespace-scoped Role to a ClusterRole
  - target:
      kind: Role
      name: keycloak-operator-role
    patch: |-
      - op: replace
        path: /kind
        value: ClusterRole

  # 3. Promote the RoleBinding to a ClusterRoleBinding
  - target:
      kind: RoleBinding
      name: keycloak-operator-role-binding
    patch: |-
      - op: replace
        path: /kind
        value: ClusterRoleBinding
      - op: replace
        path: /roleRef/kind
        value: ClusterRole