apiVersion: v1
kind: Namespace
metadata:
  name: iam
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-cert
  namespace: iam
spec:
  secretName: keycloak-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - keycloak.lab.nexusworkspace.cloud
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: iam
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv
  target:
    name: keycloak-db-secret # This creates the actual Secret Keycloak mounts
    template:
      data:
        username: "keycloak"
        admin-username: "admin"
        password: "{{ .dbpassword }}"
        admin-password: "{{ .adminpassword }}"
  data:
    - secretKey: dbpassword
      remoteRef:
        key: keycloak-db-password
    - secretKey: adminpassword
      remoteRef:
        key: keycloak-admin-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.0
          args: ["start"]
          env:
            # Tell Keycloak to accept HTTP traffic from the Ingress
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: "keycloak.lab.nexusworkspace.cloud"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://shared-postgres-pg-db-pgbouncer.database.svc.cluster.local:5432/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: admin-username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: admin-password
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: iam
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: iam
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - keycloak.lab.nexusworkspace.cloud
      secretName: keycloak-tls-cert
  rules:
    - host: keycloak.lab.nexusworkspace.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080