apiVersion: v1
kind: Namespace
metadata:
  name: iam
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-cert
  namespace: iam
spec:
  secretName: keycloak-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - keycloak.lab.nexusworkspace.cloud
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: iam
stringData:
  username: keycloak
  password: keycloakpassword
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: iam
spec:
  instances: 1
  db:
    vendor: postgres
    host: "shared-postgres-pg-db-pgbouncer.database.svc.cluster.local"
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    tlsSecret: keycloak-tls-cert
  hostname:
    hostname: keycloak.lab.nexusworkspace.cloud