apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-keycloak-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv # References your existing ClusterSecretStore
  target:
    name: keycloak-db-secret # The name of the Kubernetes Secret this will create
    template:
      data:
        # The Percona operator expects the password to be defined here
        password: "{{ .dbpassword }}"
  data:
    - secretKey: dbpassword
      remoteRef:
        key: keycloak-db-password # The exact name of the secret in Azure Key Vault