apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    # ArgoCD uses HTTPS internally, so we must tell NGINX to use HTTPS to talk to it
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # Tells External-DNS to create an A record for this exact hostname
    external-dns.alpha.kubernetes.io/hostname: "argocd.lab.nexusworkspace.cloud"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - argocd.lab.local
    secretName: argocd-tls-cert
  rules:
  - host: argocd.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443