apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 25.2.0
    chart: keycloak
    helm:
      values: |
        auth:
          adminUser: admin
          adminPassword: adminpassword
        postgresql:
          image:
            tag: 16.4.0-debian-12-r0
        production: true
        proxyHeaders: xforwarded
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hostname: keycloak.lab.nexusworkspace.cloud
          extraTls:
            - hosts:
                - keycloak.lab.nexusworkspace.cloud
              secretName: keycloak-tls-cert
# We deploy this into an 'iam' namespace to keep things organized
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: iam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true