apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 51.2.0
    chart: kube-prometheus-stack
    helm:
      values: |
        # 1. Disable Alertmanager to save RAM
        alertmanager:
          enabled: false
        
        # 2. Configure Grafana Ingress
        grafana:
          adminPassword: "admin"
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.lab.local
              
        # 3. Configure Prometheus Ingress & Lower Memory Requirements
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.lab.local
          prometheusSpec:
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true