apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/spron-in/percona-helm-charts.git'
    targetRevision: main
    path: charts/pg-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true