apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: "https://kubelab-kv-7h8owi.vault.azure.net/" # REPLACE THIS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sync-cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv
  target:
    name: cloudflare-api-token-secret # This matches what cert-manager expects
    creationPolicy: Owner
  data:
  - secretKey: api-token # The key inside the resulting k8s secret
    remoteRef:
      key: cloudflare-api-token # The name of the secret inside Azure Key Vault