apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: 14.0.0
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        image:
          registry: docker.io
          repository: bitnami/postgresql
        auth:
          postgresPassword: supersecretadmin
          username: keycloak
          password: keycloakpassword
          database: keycloak
        primary:
          persistence:
            enabled: true
            storageClass: local-path
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true