apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/spron-in/percona-helm-charts.git'
    targetRevision: main
    path: charts/pg-db
    helm:
      values: |
        users:
          - name: keycloak
            databases:
              - keycloak
        instances:
          - name: instance1
            replicas: 1
            dataVolumeClaimSpec:
              storageClassName: local-path
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true