apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-postgres
  namespace: argocd
spec:
  source:
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        image:
          registry: public.ecr.aws
          repository: bitnami/postgresql
        auth:
          postgresPassword: supersecretadmin
          username: keycloak
          password: keycloakpassword
          database: keycloak
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true